#ifndef KEST_VM_H
#define KEST_VM_H

#include "value.h"


// What this machine has said. A host reads it with `kest_report`; the command
// line wants the set rather than a rendering, because it sorts what running
// found together with what compiling did.
KestDiags *kest_runtime_said(KestRuntime *runtime);

// A machine of its own, in an arena of its own. It takes nothing from the
// build's arena: what a machine is made of goes when the machine goes, and
// what it says goes on saying it, because a diagnostic is written where the
// build's are. See D574.
// `walked` is what a walk of the whole program said, which the build works out
// once and every machine is handed: a machine sizes itself from it and holds
// every call into the host against it, and it is the same answer for every
// machine a build starts. See D607.
// The arena is the machine's and is handed in rather than taken here, because
// the machine's report has to live in it and the report exists before the
// machine does. Taking it from the build's arena instead is one bump pointer
// written by every thread that starts a machine, which is what the reference
// says a host may do. See D1071.
KestRuntime *kest_runtime_new(KestArena *own, KestModule *stamped,
                              const KestHost *host, KestDiags *diags,
                              const KestLimits *limits,
                              const KestWalk *walked);
bool kest_runtime_free(KestRuntime *runtime);

// The two doors a file this project's other backend wrote calls, and the only
// two. They are here rather than in the public header because what calls them
// is this project's own output rather than somebody's host: a generated file
// is compiled beside the library it was generated by, and the day it is not,
// the thing to write is a door a host can hold a version against. See D1094.

// Binding a body the host's compiler compiled to the chunk it was written
// from. `index` is where the body is in the module, which is what the
// generated C names it by; `symbol` is held against what is there, because a
// generated file and a program that has moved on since are two programs, and
// binding by number alone puts one body's C under another body's name.
// Answers false when there is nothing at that index, when the name there is
// another, or when that body is already bound.
bool kest_native_at(KestRuntime *runtime, uint32_t index, const char *symbol,
                    KestNativeBody body);

// The bytes of one of an array, after the two things the machine asks before
// it reads or writes one: that the handle is an array rather than something
// else or a lend the host has taken back, and that the index is inside it.
// `offset` is how far into an element a field path reached, which the
// resolved form works out while compiling and which a generated file writes
// down. NULL when it refused, and it has said why at `where` -- in the same
// words, with the same code, as the instruction that does this. What a
// generated file does with the bytes is move them itself: which piece sits
// where is known while compiling, and the walk over a layout that the machine
// does for every element is a third of `bench/rules.kest` (D1028). See D1095.
unsigned char *kest_elem_at(KestRuntime *runtime, KestValue handle,
                            int64_t index, uint16_t offset, uint32_t where);

// How many there are in one, refused the way the machine refuses it: a host
// asking the same question through `kest_array_length` is answered nought for
// a handle that is not an array, because a host may ask about anything and a
// program may not. Answers false when it refused. See D1095.
bool kest_elem_count(KestRuntime *runtime, KestValue handle, uint32_t where,
                     int64_t *into);

// What a body written in C says when it stops. `offset` is where in the source
// it was, which the resolved form carries and the C keeps beside the operation
// it came from, so a refusal from a compiled body is reported where the same
// refusal from the machine is -- with the same code, the same line, and the
// calls under it. Answers false, so a body can give back what this gives back.
bool kest_native_stopped(KestRuntime *runtime, uint32_t offset,
                         const char *code, const char *message);

#endif
